apiVersion: v1
kind: Secret
metadata:
  name: ds-auth-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{ printf "environments/secret.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}