name: Publish ds-auth to k8s staging
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Publish to Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Enable layer cache service
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build image
        run: docker build --platform=linux/amd64 -t ds-auth . --build-arg gh_token=${{ secrets.GITHUB_TOKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag ds-auth registry.digitalocean.com/ds-services-container/ds-auth
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/ds-services-container/ds-auth

  deploy:
    name: Configure and deploy to k8s staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Authenticate kubectl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ds-k8s
      - name: Write secrets
        run: "echo $'mongo_uri: \"${{ secrets.MONGO_URI_STG }}\"\nsecret: \"${{ secrets.AUTH_SECRET_STG }}\"' > ds-auth/environments/secret.stg.yaml"
      - name: Helm Deploy
        run: helm upgrade --install --create-namespace -n stg --set image.tag=latest --set namespace=stg ds-auth ds-auth
