name: Node.js Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: docker build --platform=linux/amd64 -t ds-auth . --build-arg gh_token=${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: make test-raw
